CREATE SCHEMA "applicazione";

CREATE TABLE "applicazione"."utente" (
  "utente_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar2(30) NOT NULL,
  "cognome" varchar2(30) NOT NULL,
  "data_di_nascita" date NOT NULL,
  "email" varchar2(50) UNIQUE NOT NULL,
  "password" varchar2(200) NOT NULL,
  CONSTRAINT "minorenni_non_ammessi" CHECK (data_di_nascita >= DATE '2008-01-01')
);

CREATE TABLE "applicazione"."carriera" (
  "carriera_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "studente" integer NOT NULL,
  "corso" integer NOT NULL,
  "stato" varchar2(10) NOT NULL,
  "data_inizio" date NOT NULL,
  "data_fine" date
);

CREATE TABLE "applicazione"."corso" (
  "corso_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar2(20) NOT NULL,
  "insegnamenti" integer NOT NULL,
  "tipo" varchar2(2) NOT NULL,
  "base_laurea" integer,
  "scala_voto" integer,
  "cfu_totali" integer,
  CONSTRAINT "base" CHECK (base_laurea == 60),
  CONSTRAINT "scala" CHECK (scala_voto == 110)
);

CREATE TABLE "applicazione"."insegnamento" (
  "insegnamento_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "corso" integer NOT NULL,
  "nome" varchar2(10),
  "cfu" integer,
  "anno" integer,
  "obbligatorio" bool
);

CREATE TABLE "applicazione"."esame" (
  "esame_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "insegnamento" integer NOT NULL,
  "data_esame" date
);

COMMENT ON COLUMN "applicazione"."corso"."scala_voto" IS '110';

ALTER TABLE "applicazione"."carriera" ADD CONSTRAINT "carriera_studente" FOREIGN KEY ("studente") REFERENCES "applicazione"."utente" ("utente_ID");

ALTER TABLE "applicazione"."corso" ADD CONSTRAINT "corso_di_laurea_nella_carriera" FOREIGN KEY ("corso_ID") REFERENCES "applicazione"."carriera" ("corso");

ALTER TABLE "applicazione"."insegnamento" ADD CONSTRAINT "insegnamenti_corso_di_laurea" FOREIGN KEY ("insegnamento_ID") REFERENCES "applicazione"."corso" ("insegnamenti");

ALTER TABLE "applicazione"."esame" ADD CONSTRAINT "aa" FOREIGN KEY ("insegnamento") REFERENCES "applicazione"."insegnamento" ("insegnamento_ID");
