CREATE SCHEMA "utenti";

CREATE SCHEMA "applicazione";

CREATE TABLE "utenti"."studenti" (
  "matricola" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar2(30),
  "cognome" varchar2(30),
  "data_di_nascita" date
);

CREATE TABLE "applicazione"."dati_account" (
  "studente" integer NOT NULL,
  "email" varchar2(20) UNIQUE
);

CREATE TABLE "applicazione"."carriera" (
  "carriera_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "studente" integer,
  "corso" integer,
  "stato" varchar2(10),
  "data_inizio" date,
  "data_fine" date
);

CREATE TABLE "applicazione"."corso" (
  "corso_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar2(20),
  "insegnamenti" integer,
  "tipo" varchar2(2),
  "base_laurea" integer(2),
  "scala_voto" integer(3),
  "cfu_totali" integer(3)
);

CREATE TABLE "applicazione"."insegnamento" (
  "insegnamento_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "corso" integer,
  "nome" varchar2(10),
  "cfu" integer(2),
  "anno" integer(1),
  "obbligatorio" bool
);

CREATE TABLE "applicazione"."esame" (
  "esame_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "insegnamento" integer,
  "data_esame" date
);

COMMENT ON COLUMN "applicazione"."carriera"."data_fine" IS 'opzionale';

COMMENT ON COLUMN "applicazione"."corso"."base_laurea" IS '60';

COMMENT ON COLUMN "applicazione"."corso"."scala_voto" IS '110';

ALTER TABLE "utenti"."studenti" ADD CONSTRAINT "carriera_studente" FOREIGN KEY ("matricola") REFERENCES "applicazione"."carriera" ("studente");

ALTER TABLE "utenti"."studenti" ADD CONSTRAINT "dati_studente" FOREIGN KEY ("matricola") REFERENCES "applicazione"."dati_account" ("studente");

ALTER TABLE "applicazione"."carriera" ADD CONSTRAINT "corso_di_laurea_nella_carriera" FOREIGN KEY ("corso") REFERENCES "applicazione"."corso" ("corso_ID");

ALTER TABLE "applicazione"."insegnamento" ADD CONSTRAINT "insegnamenti_corso_di_laurea" FOREIGN KEY ("insegnamento_ID") REFERENCES "applicazione"."corso" ("insegnamenti");

ALTER TABLE "applicazione"."esame" ADD CONSTRAINT "eseme_insegnemanto" FOREIGN KEY ("insegnamento") REFERENCES "applicazione"."insegnamento" ("insegnamento_ID");
