CREATE SCHEMA "applicazione";

CREATE TABLE "applicazione"."utente" (
  "utente_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar(30) NOT NULL,
  "cognome" varchar(30) NOT NULL,
  "data_di_nascita" date NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar(200) NOT NULL,
  CONSTRAINT "minorenni_non_ammessi" CHECK (data_di_nascita >= DATE '2008-01-01')
);

CREATE TABLE "applicazione"."carriera" (
  "carriera_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "studente" integer NOT NULL,
  "corso" integer NOT NULL,
  "stato" varchar(10) NOT NULL,
  "data_inizio" date NOT NULL,
  "data_fine" date
);

CREATE TABLE "applicazione"."corso" (
  "corso_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nome" varchar(20) NOT NULL,
  "insegnamenti" integer NOT NULL,
  "tipo" varchar(2) NOT NULL,
  "base_laurea" integer,
  "scala_voto" integer,
  "cfu_totali" integer,
  CONSTRAINT "base" CHECK (base_laurea = 60),
  CONSTRAINT "scala" CHECK (scala_voto = 110)
);

CREATE TABLE "applicazione"."insegnamento" (
  "insegnamento_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "corso" integer NOT NULL,
  "nome" varchar(10),
  "cfu" integer,
  "anno" integer,
  "obbligatorio" bool
);

CREATE TABLE "applicazione"."esame" (
  "esame_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "insegnamento" integer NOT NULL,
  "data_esame" date
);

COMMENT ON COLUMN "applicazione"."corso"."scala_voto" IS '110';

ALTER TABLE "applicazione"."carriera" ADD CONSTRAINT "carriera_studente" FOREIGN KEY ("studente") REFERENCES "applicazione"."utente" ("utente_id");

--ALTER TABLE "applicazione"."corso" ADD CONSTRAINT "corso_di_laurea_nella_carriera" FOREIGN KEY ("corso_id") REFERENCES "applicazione"."carriera" ("corso");
ALTER TABLE "applicazione"."carriera" ADD CONSTRAINT "carriera_fk_corso" FOREIGN KEY ("corso") REFERENCES "applicazione"."corso" ("corso_id");

--ALTER TABLE "applicazione"."insegnamento" ADD CONSTRAINT "insegnamenti_corso_di_laurea" FOREIGN KEY ("insegnamento_id") REFERENCES "applicazione"."corso" ("insegnamenti");
ALTER TABLE "applicazione"."insegnamento" ADD CONSTRAINT "insegnamenti_corso_di_laurea" FOREIGN KEY ("corso") REFERENCES "applicazione"."corso" ("corso_id");

ALTER TABLE "applicazione"."esame" ADD CONSTRAINT "aa" FOREIGN KEY ("insegnamento") REFERENCES "applicazione"."insegnamento" ("insegnamento_id");
