server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    error_page 404 = @json404;

    # Serve i file statici (Frontend)
    # location / {
    #     try_files $uri $uri/ /index.html;
    # }

    # Inoltra le chiamate API al container PHP (Backend)
    location ~ ^/api/.*$ {
        # Rimuove /api/ dall'URL prima di passarlo a PHP se necessario, 
        # oppure punta direttamente al router.php
        # Opzione A: Se usi un router.php centrale
        # try_files $uri $uri/ /api/index.php?$query_string;
        fastcgi_intercept_errors on;

        root /var/www/html;
        fastcgi_pass backend:9000; # Nome del servizio nel docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME $document_root/api/index.php;
    }

    location ~ ^/test/$ {
        fastcgi_intercept_errors on;

        root /var/www/html;
        fastcgi_pass backend:9000; # Nome del servizio nel docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /test/ {
        root /var/www/html;
        # try_files $request_filename =404;
        # try_files $uri $uri/ =404;
        # try_files $uri $uri/ /index.php?$query_string;
        # try_files $uri /var/www/html/test/style.css $uri/;
    }

    # Gestione PHP
    location ~ \.php$ {
        fastcgi_intercept_errors on;

        alias /var/www/html; # Percorso nel container BACKEND
        fastcgi_pass backend:9000; # Nome del servizio nel docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # location / {
    #     root /var/www/html;
    #     try_files $uri /var/www/html/test/style.css;
    # }

    location @json404 {
        default_type application/json;
        return 404 '{
                    "success": false,
                    "error_code": "ROUTE_ERROR",
                    "message": "The endpoint provided doesn\'t exist"
                    }';
    }
}